# Makefile frontend for scikit-build-core project
# Generated by buildgen for: cypd
#
# This Makefile wraps common build commands for convenience.
# The actual build is handled by scikit-build-core via pyproject.toml

.PHONY: all sync build rebuild test clean distclean wheel sdist check publish publish-test help reset

LIBPD := thirdparty/pure-data/lib/libpd.a

# Default target
all: build

# Install pure-data (with libpd)
$(LIBPD):
	@sh scripts/setup.sh

# Sync environment (initial setup, installs dependencies + package)
sync: $(LIBPD)
	uv sync

# Build/rebuild the extension after code changes
build: $(LIBPD)
	uv sync --reinstall-package cypd

# Alias for build
rebuild: build

# Run tests
test:
	uv run pytest tests/ -v

# Build wheel
wheel:
	uv build --wheel

# Build source distribution
sdist:
	uv build --sdist

# Check distribution with twine
check:
	uv run twine check dist/*

# Publish to PyPI
publish:
	uv run twine upload dist/*

# Publish to TestPyPI
publish-test:
	uv run twine upload --repository testpypi dist/*

# Clean build artifacts
clean:
	@rm -rf build/
	@rm -rf dist/
	@rm -rf *.egg-info/
	@rm -rf src/*.egg-info/
	@rm -rf .pytest_cache/
	@find . -name "*.so" -delete
	@find . -name "*.pyd" -delete
	@find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

# reset build-system
reset: clean
	@rm -rf thirdparty/pure-data

# Clean everything including CMake cache
distclean: clean
	@rm -rf CMakeCache.txt CMakeFiles/

# Show help
help:
	@echo "Available targets:"
	@echo "  all          - Build/rebuild the extension (default)"
	@echo "  sync         - Sync environment (initial setup)"
	@echo "  build        - Rebuild extension after code changes"
	@echo "  rebuild      - Alias for build"
	@echo "  test         - Run tests"
	@echo "  wheel        - Build wheel distribution"
	@echo "  sdist        - Build source distribution"
	@echo "  check        - Check distribution with twine"
	@echo "  publish      - Publish to PyPI"
	@echo "  publish-test - Publish to TestPyPI"
	@echo "  clean        - Remove build artifacts"
	@echo "  distclean    - Remove all generated files"
	@echo "  help         - Show this help message"
